site_name: Basic MkDocs Example Project
# Until https://github.com/readthedocs/readthedocs.org/issues/9781 is fixed, you need to
# define CUSTOM_CANONICAL_URL yourself as a workaround.
# (don't expose it to PRs, they build on different URLs)
# For instance, define it as https://SLUG.readthedocs.io/en/stable/
site_url: !ENV [READTHEDOCS_CANONICAL_URL, CUSTOM_CANONICAL_URL, ""]
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
